site_name: jsonexplore Documentation
site_description: Introspect, summarize, and navigate nested JSON structures
site_url: https://deamonpog.github.io/jsonexplore/
repo_url: https://github.com/deamonpog/jsonexplore
repo_name: deamonpog/jsonexplore

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.follow
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            merge_init_into_class: true
            separate_signature: true
            inherited_members: true
            annotations_path: brief
            filters:
              - "!^_"                        # hide private (leading underscore)
              - "!^__"                       # hide dunder
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
